### ISSUE TITLE
Getting an error in react chat 

### ISSUE THREAD

**Issue by jparvind** [ketanhwr/react-chat#1]
Hi Ketan, 

I am getting an error in the react chat, can you please fixed and update on the same repo. below are the error details

> inlaptop56:react-chat arvind$ npm start

> react-chat@1.0.0 start /Users/arvind/Desktop/react-chat
> node server

==> Listening on port 3000. Open up http://0.0.0.0:3000/ in your browser.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/arvind/Desktop/react-chat/log/app.log'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-chat@1.0.0 start: `node server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-chat@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arvind/.npm/_logs/2017-09-27T15_30_47_082Z-debug.log
inlaptop56:react-chat arvind$

**Comment by joshapearson** [comment]
I was getting the same error. It is coming from this line 

var logFile = fs.createWriteStream(path.join(__dirname, 'log/app.log'), { flags: 'a' });
It seems that it is looking for a file that does not exist inside the project. Not knowing what app.log actually does. I cannot pin down the exact nature of the failure.

**Comment by ketanhwr** [comment]
Oh shoot! I think I found what the error is. Let me try someting.

**Comment by ketanhwr** [comment]
@jparvind @joshapearson `createWriteStream` didn't throw an error when the file didn't exist previously. I guess, the new updated version throws off an error.

`log/app.log` is a file to keep track of all messages and users joining.
